* PFP Emacs Configuration

This is my literate Emacs configuration. All my Emacs configuration is embedded in this file as Emacs Lisp code blocks. To bootstrap this solution, my "regular" =init.el= file contains just a single line:

#+BEGIN_SRC elisp
(org-babel-load-file "~/.emacs.d/README.org")
#+END_SRC

The function =org-babel-load-file= extracts all Emacs Lisp code blocks into the file =README.el= and loads it.

The advantage of this approach is that the whole configuration becomes an =org-mode= document, and the outline mode makes navigating the configuration easy.

* Initialize configuration

In this section we will initialize the Emacs configuration. We will optimize startup time, customize some global settings, initialize the package system and install =use-package=.

** Use lexical binding

Configure the configuration file for lexical binding, as opposed to dynamic binding. Lexical binding is the behaviour that most developers actually expect.

#+BEGIN_SRC emacs-lisp
;;; -*- lexical-binding: t; -*-
#+END_SRC

** Upon startup, write message with startup details

Install a startup hook that informs the user of the startup duration and the number of garbage collections.

#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-startup-hook
 (lambda ()
  (message "Emacs ready in %s with %d garbage collections."
   (format "%.2f seconds"
    (float-time
     (time-subtract after-init-time before-init-time)))
   gcs-done)))
#+END_SRC

** Temporarily change garbage collection settings, and disable file-name-handler

In order to optimize the startup time we will change the garbage collection settings during startup and restore the original settings after startup is done.

#+BEGIN_SRC emacs-lisp
(let ((gc-cons-threshold-backup gc-cons-threshold)
      (gc-cons-percentage-backup gc-cons-percentage)
      file-name-handler-alist-backup file-name-handler-alist)
  ;; Change garbage collector settings and file-name-handler
  (setq gc-cons-threshold 402653184
	gc-cons-percentage 0.6
	file-name-handler-alist nil)
  ;; Then restore it as late as possible
  (add-hook 'emacs-startup-hook
	    (lambda ()
	      (message "Restored original settings")
	      (setq gc-cons-threshold gc-cons-threshold-backup
		    gc-cons-percentage gc-cons-percentage-backup
		    file-name-handler-alist (append file-name-handler-alist-backup file-name-handler-alist)))))
#+END_SRC

** Standard UI tweaks

#+BEGIN_SRC emacs-lisp
(display-battery-mode t)
(display-time-mode t)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
#+END_SRC

** Enable linum for programming modes

#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook #'linum-mode)
#+END_SRC

** Configure =custom-file=

Do not use =init.el= for =custom-*= code - use =custom.el=.

#+BEGIN_SRC emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
#+END_SRC

Assuming that the code in custom-file is executed before the code ahead of this line is not a safe assumption. So load this file proactively.

#+BEGIN_SRC emacs-lisp
(when (file-exists-p custom-file)
  (load custom-file))
#+END_SRC

** Require and initialize =package=

#+BEGIN_SRC emacs-lisp
(require 'package)
(package-initialize)
#+END_SRC

*** Add =melpa= to =package-archives=

#+BEGIN_SRC emacs-lisp
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archive-priorities '("melpa" . 10) t)
#+END_SRC

** Install =use-package=

#+BEGIN_SRC emacs-lisp
(when (not (package-installed-p 'use-package))
 (package-refresh-contents)
 (package-install 'use-package))
#+END_SRC

* Utility functions
** Install =memoize=

=memoize= is a great library that can memoize functions.

For example the following code produces the output below.

#+BEGIN_SRC elisp :results output session :exports both
(defvar square-times-called 0)
(defmemoize-by-buffer-contents square (x)
  (setq square-times-called (+ square-times-called 1))
  (print (format "Called `square' for the %d-th time." square-times-called))
  (* x x))

(print (square 6))
(print (square 6))
(print (square 5))
#+END_SRC

#+RESULTS:
#+begin_example

"Called `square' for the 1-th time."

36

36

"Called `square' for the 2-th time."

25
#+end_example

Memoize is used by some utility functions.

#+BEGIN_SRC emacs-lisp
(use-package memoize
 :ensure t)
#+END_SRC

** =pfp-recompile-user-dir=

#+BEGIN_SRC emacs-lisp
(defun pfp-recompile-user-dir ()
 "Recompile everything in the `package-user-dir'."
 (interactive)
 (byte-recompile-directory package-user-dir nil 'force))
#+END_SRC

** =pfp-command-exists-p=

#+BEGIN_SRC emacs-lisp
(defmemoize pfp-command-exists-p (command)
  "Checks whether COMMAND exists on this system.

The existence of COMMAND is checked using =which COMMAND=. So this function
will only work on systems where the command =which= exists."
  (let ((buf    (get-buffer-create "command-exists-buffer"))
        (retval nil))
    (setq retval (shell-command (format "which '%s'" command)))
    (kill-buffer buf)
    (eq retval 0)))
#+END_SRC

* Look and Feel
** Install =all-the-icons=

To use =all-the-icons=, one must run =M-x all-the-icons-install-fonts=.

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons
 :ensure t
 :if (display-graphic-p))
#+END_SRC

** Install =doom-themes=

From [[https://github.com/hlissner/emacs-doom-themes]]

#+BEGIN_SRC emacs-lisp
(use-package doom-themes
 :after (treemacs)
 :ensure t
 :config
 ;; Global settings (defaults)
 (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
       doom-themes-enable-italic t) ; if nil, italics is universally disabled
 (load-theme 'doom-nord t)

 ;; Enable flashing mode-line on errors
 (doom-themes-visual-bell-config)

 ;; Enable custom neotree theme (all-the-icons must be installed!)
 ;; (doom-themes-neotree-config)
 ;; or for treemacs users
 (setq doom-themes-treemacs-theme "doom-colors") ; use the colorful treemacs theme
 (doom-themes-treemacs-config)

 ;; Corrects (and improves) org-mode's native fontification.
 (doom-themes-org-config))
#+END_SRC

** Install =doom-modeline=

From [[https://github.com/seagle0128/doom-modeline]]

#+BEGIN_SRC emacs-lisp
(use-package doom-modeline
 :ensure t
 :init (doom-modeline-mode 1))
#+END_SRC

** Install =minimap=

#+BEGIN_SRC emacs-lisp
  ;; Minimap
  (use-package minimap
    :ensure t
    :if (display-graphic-p)
    :config
    (global-set-key [f9] 'minimap-mode)
    :init
    (setq minimap-window-location 'right)
    :custom-face
    (minimap-active-region-background ((t (:background "#4C566A"))))
    (minimap-current-line-face ((t (:background "#88C0D0" :foreground "#2E3440")))))
#+END_SRC

** Install =beacon=

Shortly highlights the cursor position when switching buffers.

#+BEGIN_SRC emacs-lisp
(use-package beacon
  :ensure t
  :config (beacon-mode 1))
#+END_SRC

* Install =restart-emacs=

#+BEGIN_SRC emacs-lisp
(use-package restart-emacs
 :ensure t
 :defer t)
#+END_SRC

* Navigation
** Install =counsel ivy and swiper=

See: [[https://writequit.org/denver-emacs/presentations/2017-04-11-ivy.html]]

Configuration from: [[https://github.com/abo-abo/swiper]]

Some of these configurations depend on external software:

- =ag=
- =locate= (=mlocate= or =slocate=)
- =rhythmbox=
- =git=

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :ensure t
  :config
  (progn
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t)
    (setq ivy-count-format "%d of %d - ")
    ;; enable this if you want `swiper' to use it
    ;; (setq search-default-mode #'char-fold-to-regexp)
    (global-set-key (kbd "C-S-s") 'swiper)
    (global-set-key (kbd "C-c C-r") 'ivy-resume)
    (global-set-key (kbd "<f6>") 'ivy-resume)
    ;; (global-set-key (kbd "M-x") 'counsel-M-x)
    ;; (global-set-key (kbd "C-x C-f") 'counsel-find-file)
    ;; (global-set-key (kbd "<f1> f") 'counsel-describe-function)
    ;; (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
    (global-set-key (kbd "<f1> o") 'counsel-describe-symbol)
    ;; (global-set-key (kbd "<f1> l") 'counsel-find-library)
    ;; (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
    (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
    (global-set-key (kbd "C-c g") 'counsel-git)
    (global-set-key (kbd "C-c j") 'counsel-git-grep)
    (global-set-key (kbd "C-c k") 'counsel-ag)
    (global-set-key (kbd "C-x l") 'counsel-locate)
    (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
    (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package counsel
  :ensure t
  :after (ivy)
  :config (counsel-mode 1))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package counsel-tramp
  :ensure t
  :defer t
  :after (counsel))
#+END_SRC

*** Show icons in ivy

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons-ivy
 :ensure t
 :after (all-the-icons ivy)
 :if (display-graphic-p)
 :config
 (all-the-icons-ivy-setup))
#+END_SRC

** Install =avy=

#+BEGIN_SRC emacs-lisp
(use-package avy
  :ensure t
  ;; :defer t
  :bind (("C-:" . avy-goto-char)
	 ("C-'" . avy-goto-char2)
	 ("M-g f" . avy-goto-line)
	 ("M-g w" . avy-goto-word-1)
	 ("M-g e" . avy-goto-word-0)
	 ("C-c C-j" . avy-resume))
  :config
  (avy-setup-default))
#+END_SRC

* Editing
** =multiple-cursors=

#+BEGIN_SRC emacs-lisp
(use-package multiple-cursors
  :ensure t
  :defer t
  :config
  (progn
    (global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
    (global-set-key (kbd "C->") 'mc/mark-next-like-this)
    (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
    (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
    ))
#+END_SRC

*** TODO after startup the keybindings above don't work
** =yasnippet=

#+BEGIN_SRC emacs-lisp
(require 'f)
(unless (f-directory? "~/.emacs.d/snippets")
 (mkdir "~/.emacs.d/snippets"))

(use-package yasnippet
  :ensure t
  :config
  (progn
    (yas-load-directory "~/.emacs.d/snippets")
    (yas-global-mode 1)))

(use-package yasnippet-snippets
  :ensure t
  :after (yasnippet))
#+END_SRC
** =string-inflection=

#+BEGIN_SRC emacs-lisp
(use-package string-inflection
  :ensure t
  :config (progn
            (global-set-key (kbd "C-c i") 'string-inflection-cycle)
            (global-set-key (kbd "C-c C") 'string-inflection-camelcase)        ;; Force to CamelCase
            (global-set-key (kbd "C-c L") 'string-inflection-lower-camelcase)  ;; Force to lowerCamelCase
            (global-set-key (kbd "C-c J") 'string-inflection-java-style-cycle) ;; Cycle through Java styles
            ))
#+END_SRC
** =editorconfig=

#+BEGIN_SRC emacs-lisp
(use-package editorconfig
  :ensure t
  :config
  (editorconfig-mode 1))
#+END_SRC
** Code completion with =company=

#+BEGIN_SRC emacs-lisp
(use-package company
  :ensure t
  :config (add-hook 'after-init-hook 'global-company-mode))

(use-package company-box
  :ensure t
  :hook (company-mode . company-box-mode))

;; Additional completion packages
(use-package company-lsp
  :ensure t
  :after (company lsp-mode)
  :commands company-lsp
  :init (add-to-list 'company-backends #'company-lsp)
  :config (setq company-lsp-enable-snippet t
                company-lsp-cache-candidates t))

(use-package company-quickhelp
  :ensure t
  :after (company)
  :config (progn (company-quickhelp-mode 1)
                 (with-eval-after-load 'company-mode
                   (define-key company-active-map (kbd "C-c h") #'company-quickhelp-manual-begin))))

(use-package company-web
  :ensure t)
#+END_SRC
** Syntax checking with =flycheck=

#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :hook (prog-mode . flycheck-mode)
  :config
  (progn
    (setq flycheck-check-syntax-automatically '(save new-line))))
#+END_SRC
*** Syntax checking of packages

#+BEGIN_SRC emacs-lisp
(use-package flycheck-package
  :ensure t
  :after (flycheck))
#+END_SRC

* System utilities and tools
** Silver searcher

#+BEGIN_SRC emacs-lisp
(use-package ag
  :ensure t
  :if (pfp-command-exists-p 'ag))
#+END_SRC

** Ripgrep

#+BEGIN_SRC emacs-lisp
(use-package ripgrep
  :ensure t
  :if (pfp-command-exists-p 'rg))
(use-package rg
  :ensure t
  :if (pfp-command-exists-p 'rg))
#+END_SRC

*** TODO Investigate whether both are needed

** Lastpass

#+BEGIN_SRC emacs-lisp
(use-package lastpass
  :ensure
  :if (pfp-command-exists-p 'lpass))
#+END_SRC

** Gnuplot

#+BEGIN_SRC emacs-lisp
(use-package gnuplot
  :ensure t
  :if (pfp-command-exists-p 'gnuplot)
  :config
  (progn
    ;; these lines enable the use of gnuplot mode
    (autoload 'gnuplot-mode "gnuplot" "gnuplot major mode" t)
    (autoload 'gnuplot-make-buffer "gnuplot" "open a buffer in gnuplot mode" t)

    ;; this line automatically causes all files with the .gp extension to be loaded into gnuplot mode
    (setq auto-mode-alist (append '(("\\.gp$" . gnuplot-mode)) auto-mode-alist))

    ;; This line binds the function-9 key so that it opens a buffer into gnuplot mode
    ;; (global-set-key [(f9)] 'gnuplot-make-buffer)
    ))
#+END_SRC

** Docker

#+BEGIN_SRC emacs-lisp
(use-package docker
  :ensure t
  :if (pfp-command-exists-p 'docker)
  :bind ("C-c d" . docker))
#+END_SRC

** Vagrant

#+BEGIN_SRC emacs-lisp
(use-package vagrant
  :ensure t
  :if (pfp-command-exists-p 'vagrant))
#+END_SRC

** PlantUML

- Reference Guide: [[http://plantuml.com/PlantUML_Language_Reference_Guide.pdf]]
- Download from: [[https://sourceforge.net/projects/plantuml/files/plantuml.jar/download]]

#+BEGIN_SRC emacs-lisp
(use-package plantuml-mode
  :ensure t
  :config
  (progn
    (add-to-list 'auto-mode-alist '("\\.puml\\'" . plantuml-mode))
    (add-to-list 'auto-mode-alist '("\\.plantuml\\'" . plantuml-mode))))
#+END_SRC

* File management
** Colorize =dired= with =diredfl=

#+BEGIN_SRC emacs-lisp
(use-package diredfl
  :ensure t
  :config
  (diredfl-global-mode))
#+END_SRC
** Show icons in =dired= with =all-the-icons-dired=

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons-dired
 :ensure t
 :after (all-the-icons)
 :if (display-graphic-p)
 :config
 (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+END_SRC

** Install =treemacs=

#+BEGIN_SRC emacs-lisp
(use-package treemacs
 :ensure t
 :config (global-set-key [f8] 'treemacs))
#+END_SRC
* Version Control
** Install =diff-hl=

[[https://github.com/dgutov/diff-hl][diff-hl-mode]] highlights uncommitted changes on the left size of the window.

#+BEGIN_SRC emacs-lisp
(use-package diff-hl
  :ensure t
  :after (magit)
  :config
  (progn
   (global-diff-hl-mode)
   ;; (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
   (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)))
#+END_SRC

** Git
*** Install =magit=

#+BEGIN_SRC emacs-lisp
(use-package magit
 :ensure t
 :if (pfp-command-exists-p 'git)
 :defer t)
#+END_SRC

*** Install =forge=

#+BEGIN_SRC emacs-lisp
(use-package forge
  :ensure t
  :if (pfp-command-exists-p 'git)
  :after (magit))
#+END_SRC

* Project management
** =projectile=

#+BEGIN_SRC emacs-lisp
(use-package projectile
 :ensure t
 :defer t)
(use-package projectile-ripgrep
  :ensure t
  :defer t
  :after (projectile)
  :if (pfp-command-exists-p 'rg))
(use-package term-projectile
 :ensure t
 :defer t)
(use-package treemacs-projectile
  :ensure t
  :defer t
  :after (treemacs projectile))
#+END_SRC

* Terminals
** Install =vterm=

#+BEGIN_SRC emacs-lisp
(use-package vterm
 :ensure t
 :defer t
 :init
 (progn
  (setq vterm-always-compile-module t)))
#+END_SRC
** =eshell= customization

#+BEGIN_SRC emacs-lisp
(use-package eshell-git-prompt
  :ensure t
  :config
  (eshell-git-prompt-use-theme 'powerline))
#+END_SRC

* Web

** =restclient=

#+BEGIN_SRC emacs-lisp
(use-package restclient
 :ensure t)
#+END_SRC

* File type
** =csv-mode=

#+BEGIN_SRC emacs-lisp
(use-package csv-mode
  :ensure t
  :config
  (progn
    (add-to-list 'auto-mode-alist '("\\.[Cc][Ss][Vv]\\'" . csv-mode))
    ))
#+END_SRC
** =yaml-mode=

#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
 :ensure t)
#+END_SRC
** =json-mode=

#+BEGIN_SRC emacs-lisp
(use-package json-mode
 :ensure t)
#+END_SRC

* Markup languages
** Org-mode
*** =htmlize=

 #+BEGIN_SRC emacs-lisp
 (use-package htmlize
  :ensure t
  :defer t)
 #+END_SRC
*** =org-bullets=

#+BEGIN_SRC emacs-lisp
(use-package org-bullets
  :ensure t
  :after (org)
  :commands (org-bullets-mode)
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

** Markdown

 #+BEGIN_SRC emacs-lisp
 (use-package markdown-mode
  :ensure t)

 (defun markdown-backward-inner-block ()
   "Navigate back to the beginning of this block."
   (markdown-backward-block)
   (forward-line))

 (defun markdown-forward-inner-block ()
   "Navigate forward to the end of this block."
   (markdown-forward-block)
   (previous-line))

 (defun markdown-narrow-inner-block ()
   "Make text inside current block visible.
 The current block is the one that contains point or follows point."
   (interactive)
   (let ((beginning-of-defun-function 'markdown-backward-inner-block)
         (end-of-defun-function 'markdown-forward-inner-block))
     (narrow-to-defun)))
 #+END_SRC

* Programming
** Emacs Lisp

#+BEGIN_SRC emacs-lisp
(use-package rainbow-mode
 :ensure t)
(use-package rainbow-delimiters
  :ensure t
  :config
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
(use-package highlight-defined
  :ensure t
  :config
  (add-hook 'emacs-lisp-mode-hook 'highlight-defined-mode))
(use-package smartparens
  :ensure t
  :config
  (require 'smartparens-config))
#+END_SRC

** =lsp-mode=

Installation copied from: [[https://emacs-lsp.github.io/lsp-mode/page/installation/]]

#+BEGIN_SRC emacs-lisp
;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
(setq lsp-keymap-prefix "s-l")

(use-package lsp-mode
    :ensure t
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
            ;; (XXX-mode . lsp)
            ;; (XXX-mode . lsp-deferred) ;; to defer LSP server startup
            ;; if you want which-key integration
            (lsp-mode . lsp-enable-which-key-integration))
    :commands lsp lsp-deferred)

;; optionally
(use-package lsp-ui
 :ensure t
 :commands lsp-ui-mode)
;; if you are helm user
;; (use-package helm-lsp :commands helm-lsp-workspace-symbol)
;; if you are ivy user
(use-package lsp-ivy
 :ensure t
 :commands lsp-ivy-workspace-symbol)
(use-package lsp-treemacs
 :ensure t
 :commands lsp-treemacs-errors-list)

;; optionally if you want to use debugger
(use-package dap-mode
 :ensure t)
;; (use-package dap-LANGUAGE) to load the dap adapter for your language

;; optional if you want which-key integration
(use-package which-key
    :ensure t
    :config
    (which-key-mode))
#+END_SRC

** Cucumber =feature-mode=

Install [[https://github.com/michaelklishin/cucumber.el][=feature-mode=]] to edit plain text user stories.

#+BEGIN_SRC emacs-lisp
(use-package feature-mode
 :ensure t)
#+END_SRC

* EXWM
** Install =exwm=

#+BEGIN_SRC emacs-lisp
(use-package exwm
 :ensure t
 :if (display-graphic-p)
 :config
 (progn
  ;; Turn on `display-time-mode' if you don't use an external bar.
  (setq display-time-default-load-average nil)
  (display-time-mode t)

  ;; You are strongly encouraged to enable something like `ido-mode' to alter
  ;; the default behavior of 'C-x b', or you will take great pains to switch
  ;; to or back from a floating frame (remember 'C-x 5 o' if you refuse this
  ;; proposal however).
  ;; You may also want to call `exwm-config-ido' later (see below).
  ;; (ido-mode 1)

  ;;;; Below are configurations for EXWM.

  ;; Add paths (not required if EXWM is installed from GNU ELPA).
  ;(add-to-list 'load-path "/path/to/xelb/")
  ;(add-to-list 'load-path "/path/to/exwm/")

  ;; Load EXWM.
  (require 'exwm)

  ;; Fix problems with Ido (if you use it).
  (require 'exwm-config)
  ;; (exwm-config-ido)

  ;; Set the initial number of workspaces (they can also be created later).
  (setq exwm-workspace-number 4)

  ;; All buffers created in EXWM mode are named "*EXWM*". You may want to
  ;; change it in `exwm-update-class-hook' and `exwm-update-title-hook', which
  ;; are run when a new X window class name or title is available.  Here's
  ;; some advice on this topic:
  ;; + Always use `exwm-workspace-rename-buffer' to avoid naming conflict.
  ;; + For applications with multiple windows (e.g. GIMP), the class names of
  ;;   all windows are probably the same.  Using window titles for them makes
  ;;   more sense.
  ;; In the following example, we use class names for all windows expect for
  ;; Java applications and GIMP.
  (add-hook 'exwm-update-class-hook
            (lambda ()
              (unless (or (string-prefix-p "sun-awt-X11-" exwm-instance-name)
                          (string= "gimp" exwm-instance-name))
                (exwm-workspace-rename-buffer exwm-class-name))))
  (add-hook 'exwm-update-title-hook
            (lambda ()
              (when (or (not exwm-instance-name)
                        (string-prefix-p "sun-awt-X11-" exwm-instance-name)
                        (string= "gimp" exwm-instance-name))
                (exwm-workspace-rename-buffer exwm-title))))

  ;; Global keybindings can be defined with `exwm-input-global-keys'.
  ;; Here are a few examples:
  (setq exwm-input-global-keys
        `(
          ;; Bind "s-r" to exit char-mode and fullscreen mode.
          ([?\s-r] . exwm-reset)
          ;; Bind "s-w" to switch workspace interactively.
          ([?\s-w] . exwm-workspace-switch)
          ;; Bind "s-0" to "s-9" to switch to a workspace by its index.
          ,@(mapcar (lambda (i)
                      `(,(kbd (format "s-%d" i)) .
                        (lambda ()
                          (interactive)
                          (exwm-workspace-switch-create ,i))))
                    (number-sequence 0 9))
          ;; Bind "s-&" to launch applications ('M-&' also works if the output
          ;; buffer does not bother you).
          ([?\s-&] . (lambda (command)
    	           (interactive (list (read-shell-command "$ ")))
    	           (start-process-shell-command command nil command)))
          ;; Bind "s-<f2>" to "slock", a simple X display locker.
          ([s-f2] . (lambda ()
    	          (interactive)
    	          (start-process "" nil "/usr/bin/slock")))))

  ;; To add a key binding only available in line-mode, simply define it in
  ;; `exwm-mode-map'.  The following example shortens 'C-c q' to 'C-q'.
  (define-key exwm-mode-map [?\C-q] #'exwm-input-send-next-key)

  ;; The following example demonstrates how to use simulation keys to mimic
  ;; the behavior of Emacs.  The value of `exwm-input-simulation-keys' is a
  ;; list of cons cells (SRC . DEST), where SRC is the key sequence you press
  ;; and DEST is what EXWM actually sends to application.  Note that both SRC
  ;; and DEST should be key sequences (vector or string).
  (setq exwm-input-simulation-keys
        '(
          ;; movement
          ([?\C-b] . [left])
          ([?\M-b] . [C-left])
          ([?\C-f] . [right])
          ([?\M-f] . [C-right])
          ([?\C-p] . [up])
          ([?\C-n] . [down])
          ([?\C-a] . [home])
          ([?\C-e] . [end])
          ([?\M-v] . [prior])
          ([?\C-v] . [next])
          ([?\C-d] . [delete])
          ([?\C-k] . [S-end delete])
          ;; cut/paste.
          ([?\C-w] . [?\C-x])
          ([?\M-w] . [?\C-c])
          ([?\C-y] . [?\C-v])
          ;; search
          ([?\C-s] . [?\C-f])))

  ;; You can hide the minibuffer and echo area when they're not used, by
  ;; uncommenting the following line.
  ;; (setq exwm-workspace-minibuffer-position 'bottom)

  ;; RandR
  (require 'exwm-randr)
  (exwm-randr-enable)

  ;; System tray
  (require 'exwm-systemtray)
  (exwm-systemtray-enable)))
#+END_SRC

* End

#+BEGIN_SRC emacs-lisp
(provide 'pfp)
;;; pfp ends here
#+END_SRC
